### ISSUE TITLE
Keyboard lexicon bug

### ISSUE THREAD

**Issue by ydkhatri** [abrignoni/iLEAPP#172]
Got an error when running with type `fs` on windows.
```
Keyboard Dynamic Lexicon [keyboardLexicon] artifact executing
Reading Keyboard Dynamic Lexicon artifact had errors!
Error was list index out of range
Exception Traceback: Traceback (most recent call last):
  File "C:\Github\iLEAPP\scripts\ilap_artifacts.py", line 261, in process_artifact
    method(files_found, report_folder, seeker)
  File "C:\Github\iLEAPP\scripts\artifacts\keyboardLexicon.py", line 26, in get_keyboardLexicon
    location_file_found = file_found.split("Keyboard/", 1)[1]
IndexError: list index out of range
```

**Comment by ydkhatri** [comment]
OK, I just fixed this in #174
