### ISSUE TITLE
ileappGUI.py won't run...

### ISSUE THREAD

**Issue by ChopOMatic** [abrignoni/iLEAPP#277]
I installed this on a Win11 laptop via WSL2->Ubuntu->Homebrew->Python3->git clone ileapp->brew install requirements.txt
Runs fine. No issues.

I repeated the exact process on a Windows 10 workstation and have had nothing but issues:

```
anvil@acme:~/iLEAPP$ python3 ileappGUI.py
Traceback (most recent call last):
  File "/home/vflab/iLEAPP/ileappGUI.py", line 1, in <module>
    import ileapp
  File "/home/vflab/iLEAPP/ileapp.py", line 4, in <module>
    import scripts.report as report
  File "/home/vflab/iLEAPP/scripts/report.py", line 10, in <module>
    from scripts.ilapfuncs import logfunc
  File "/home/vflab/iLEAPP/scripts/ilapfuncs.py", line 16, in <module>
    from bs4 import BeautifulSoup
ModuleNotFoundError: No module named 'bs4'
anvil@acme:~/iLEAPP$ pip3 install bs4
DEPRECATION: Configuring installation scheme with distutils config files is deprecated and will no longer work in the near future. If you are using a Homebrew or Linuxbrew Python, please see discussion at https://github.com/Homebrew/homebrew-core/issues/76621
Collecting bs4
  Using cached bs4-0.0.1-py3-none-any.whl
Collecting beautifulsoup4
  Using cached beautifulsoup4-4.10.0-py3-none-any.whl (97 kB)
Collecting soupsieve>1.2
  Using cached soupsieve-2.3.1-py3-none-any.whl (37 kB)
Installing collected packages: soupsieve, beautifulsoup4, bs4
  DEPRECATION: Configuring installation scheme with distutils config files is deprecated and will no longer work in the near future. If you are using a Homebrew or Linuxbrew Python, please see discussion at https://github.com/Homebrew/homebrew-core/issues/76621
  DEPRECATION: Configuring installation scheme with distutils config files is deprecated and will no longer work in the near future. If you are using a Homebrew or Linuxbrew Python, please see discussion at https://github.com/Homebrew/homebrew-core/issues/76621
  DEPRECATION: Configuring installation scheme with distutils config files is deprecated and will no longer work in the near future. If you are using a Homebrew or Linuxbrew Python, please see discussion at https://github.com/Homebrew/homebrew-core/issues/76621
DEPRECATION: Configuring installation scheme with distutils config files is deprecated and will no longer work in the near future. If you are using a Homebrew or Linuxbrew Python, please see discussion at https://github.com/Homebrew/homebrew-core/issues/76621
Successfully installed beautifulsoup4-4.10.0 bs4-0.0.1 soupsieve-2.3.1
anvil@acme:~/iLEAPP$ python3 ileappGUI.py
Traceback (most recent call last):
  File "/home/vflab/iLEAPP/ileappGUI.py", line 1, in <module>
    import ileapp
  File "/home/vflab/iLEAPP/ileapp.py", line 4, in <module>
    import scripts.report as report
  File "/home/vflab/iLEAPP/scripts/report.py", line 10, in <module>
    from scripts.ilapfuncs import logfunc
  File "/home/vflab/iLEAPP/scripts/ilapfuncs.py", line 17, in <module>
    from PIL import Image
ModuleNotFoundError: No module named 'PIL'
```

**Comment by stark4n6** [comment]
Looks like PIL is missing from the requirements doc, try manually importing that or adding it as a line in the requirements then rerunning the process.

**Comment by abrignoni** [comment]
PIL is no missing. It is part of the pillow library which is already part of requirements.txt
If requirements.txt was run then the bs4 module not found error (as well as the pil one) wouldn't have occurred.
Do "pip3 install -r requirements.txt" and try again.

**Comment by ChopOMatic** [comment]
I definitely ran both "sudo apt-get install python3-tk" and "pip3 install -r requirements.txt" before attempting to run it.

**Comment by abrignoni** [comment]
Then there must have definitely been some issue when you ran it since bs4 and PIL (part of pillow) where not found and both are contained in the requirements.txt file. Try to pip install pillow and try again. Either way the issue is not in iLEAPP's code since your system has not met the module/library requirements yet. As you know when the requirements are met the scripts run as expected with no issues.

**Comment by ChopOMatic** [comment]
I re-ran "pip3 install -r requirements.txt." Here's the output:

```
pip3 install -r requirements.txt
DEPRECATION: Configuring installation scheme with distutils config files is deprecated and will no longer work in the near future. If you are using a Homebrew or Linuxbrew Python, please see discussion at https://github.com/Homebrew/homebrew-core/issues/76621
Ignoring python-magic-bin: markers 'platform_system == "Windows"' don't match your environment
Ignoring python-magic-bin: markers 'platform_system == "Darwin"' don't match your environment
Collecting numpy==1.21.4
  Using cached numpy-1.21.4-cp39-cp39-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (15.7 MB)
Collecting astc_decomp
  Using cached astc_decomp-1.0.3.tar.gz (58 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: biplist in /home/linuxbrew/.linuxbrew/lib/python3.9/site-packages (from -r requirements.txt (line 3)) (1.0.3)
Requirement already satisfied: bs4 in /home/linuxbrew/.linuxbrew/lib/python3.9/site-packages (from -r requirements.txt (line 4)) (0.0.1)
Collecting pyliblzfse
  Using cached pyliblzfse-0.4.1.tar.gz (47 kB)
  Preparing metadata (setup.py) ... done
Collecting packaging==20.1
  Using cached packaging-20.1-py2.py3-none-any.whl (36 kB)
Collecting pathlib2==2.3.5
  Using cached pathlib2-2.3.5-py2.py3-none-any.whl (18 kB)
Collecting PGPy
  Using cached PGPy-0.5.4-py2.py3-none-any.whl (84 kB)
Requirement already satisfied: pillow in /home/linuxbrew/.linuxbrew/lib/python3.9/site-packages (from -r requirements.txt (line 9)) (9.0.1)
Collecting pyinstaller
  Using cached pyinstaller-4.9-py3-none-manylinux2014_x86_64.whl (1.5 MB)
Requirement already satisfied: PySimpleGUI==4.16.0 in /home/linuxbrew/.linuxbrew/lib/python3.9/site-packages (from -r requirements.txt (line 11)) (4.16.0)
Collecting blackboxprotobuf
  Using cached blackboxprotobuf-1.0.1-py3-none-any.whl
Collecting nska-deserialize>=1.3.1
  Using cached nska_deserialize-1.3.2-py3-none-any.whl
Requirement already satisfied: simplekml in /home/linuxbrew/.linuxbrew/lib/python3.9/site-packages (from -r requirements.txt (line 15)) (1.3.6)
Collecting pandas
  Using cached pandas-1.4.1-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (11.7 MB)
Collecting pycryptodome
  Using cached pycryptodome-3.14.1-cp35-abi3-manylinux2010_x86_64.whl (2.0 MB)
Collecting python-magic==0.4.24
  Using cached python_magic-0.4.24-py2.py3-none-any.whl (12 kB)
Collecting pyparsing>=2.0.2
  Using cached pyparsing-3.0.7-py3-none-any.whl (98 kB)
Requirement already satisfied: six in /home/linuxbrew/.linuxbrew/lib/python3.9/site-packages (from packaging==20.1->-r requirements.txt (line 6)) (1.16.0)
Requirement already satisfied: beautifulsoup4 in /home/linuxbrew/.linuxbrew/lib/python3.9/site-packages (from bs4->-r requirements.txt (line 4)) (4.10.0)
Collecting cryptography>=2.6
  Using cached cryptography-36.0.1-cp36-abi3-manylinux_2_24_x86_64.whl (3.6 MB)
Collecting pyasn1
  Using cached pyasn1-0.4.8-py2.py3-none-any.whl (77 kB)
Collecting altgraph
  Using cached altgraph-0.17.2-py2.py3-none-any.whl (21 kB)
Requirement already satisfied: setuptools in /home/linuxbrew/.linuxbrew/lib/python3.9/site-packages (from pyinstaller->-r requirements.txt (line 10)) (60.5.0)
Collecting pyinstaller-hooks-contrib>=2020.6
  Using cached pyinstaller_hooks_contrib-2022.2-py2.py3-none-any.whl (223 kB)
Collecting protobuf==3.10.0
  Using cached protobuf-3.10.0-py2.py3-none-any.whl (434 kB)
Requirement already satisfied: pytz>=2020.1 in /home/linuxbrew/.linuxbrew/lib/python3.9/site-packages (from pandas->-r requirements.txt (line 16)) (2021.3)
Collecting python-dateutil>=2.8.1
  Using cached python_dateutil-2.8.2-py2.py3-none-any.whl (247 kB)
Collecting cffi>=1.12
  Using cached cffi-1.15.0-cp39-cp39-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (444 kB)
Requirement already satisfied: soupsieve>1.2 in /home/linuxbrew/.linuxbrew/lib/python3.9/site-packages (from beautifulsoup4->bs4->-r requirements.txt (line 4)) (2.3.1)
Collecting pycparser
  Using cached pycparser-2.21-py2.py3-none-any.whl (118 kB)
Building wheels for collected packages: astc_decomp, pyliblzfse
  Building wheel for astc_decomp (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [12 lines of output]
      /home/linuxbrew/.linuxbrew/opt/python@3.9/lib/python3.9/site-packages/setuptools/dist.py:723: UserWarning: Usage of dash-separated 'description-file' will not be supported in future versions. Please use the underscore name 'description_file' instead
        warnings.warn(
      /home/linuxbrew/.linuxbrew/opt/python@3.9/lib/python3.9/site-packages/setuptools/dist.py:723: UserWarning: Usage of dash-separated 'long-description' will not be supported in future versions. Please use the underscore name 'long_description' instead
        warnings.warn(
      running bdist_wheel
      running build
      running build_ext
      creating build
      creating build/temp.linux-x86_64-3.9
      creating build/temp.linux-x86_64-3.9/astc_dec
      gcc-5 -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -O3 -Wall -fPIC -Iastc_dec -I/home/linuxbrew/.linuxbrew/opt/python@3.9/include/python3.9 -c astc_dec/astc_decomp.cpp -o build/temp.linux-x86_64-3.9/astc_dec/astc_decomp.o
      error: command 'gcc-5' failed: No such file or directory
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for astc_decomp
  Running setup.py clean for astc_decomp
  Building wheel for pyliblzfse (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [9 lines of output]
      running bdist_wheel
      running build
      running build_ext
      creating build
      creating build/temp.linux-x86_64-3.9
      creating build/temp.linux-x86_64-3.9/lzfse
      creating build/temp.linux-x86_64-3.9/lzfse/src
      gcc-5 -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -O3 -Wall -fPIC -Ilzfse/src -I/home/linuxbrew/.linuxbrew/opt/python@3.9/include/python3.9 -c lzfse/src/lzfse_decode.c -o build/temp.linux-x86_64-3.9/lzfse/src/lzfse_decode.o -std=c99
      error: command 'gcc-5' failed: No such file or directory
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pyliblzfse
  Running setup.py clean for pyliblzfse
Failed to build astc_decomp pyliblzfse
Installing collected packages: pyliblzfse, pyasn1, astc_decomp, altgraph, python-magic, python-dateutil, pyparsing, pyinstaller-hooks-contrib, pycryptodome, pycparser, protobuf, pathlib2, numpy, nska-deserialize, pyinstaller, pandas, packaging, cffi, blackboxprotobuf, cryptography, PGPy
  DEPRECATION: Configuring installation scheme with distutils config files is deprecated and will no longer work in the near future. If you are using a Homebrew or Linuxbrew Python, please see discussion at https://github.com/Homebrew/homebrew-core/issues/76621
  Running setup.py install for pyliblzfse ... error
  error: subprocess-exited-with-error

  × Running setup.py install for pyliblzfse did not run successfully.
  │ exit code: 1
  ╰─> [11 lines of output]
      running install
      /home/linuxbrew/.linuxbrew/opt/python@3.9/lib/python3.9/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        warnings.warn(
      running build
      running build_ext
      creating build
      creating build/temp.linux-x86_64-3.9
      creating build/temp.linux-x86_64-3.9/lzfse
      creating build/temp.linux-x86_64-3.9/lzfse/src
      gcc-5 -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -O3 -Wall -fPIC -Ilzfse/src -I/home/linuxbrew/.linuxbrew/opt/python@3.9/include/python3.9 -c lzfse/src/lzfse_decode.c -o build/temp.linux-x86_64-3.9/lzfse/src/lzfse_decode.o -std=c99
      error: command 'gcc-5' failed: No such file or directory
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> pyliblzfse

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.
```

**Comment by abrignoni** [comment]
Seems homebrew / Linuxbrew is the issue. Try again without using it.
