### ISSUE TITLE
booking.py error notification

### ISSUE THREAD

**Issue by ScottKjr3347** [abrignoni/iLEAPP#774]
Receiving the following error for the new "booking.py" when attempting to launch ileappGUI.py:

PS C:\Users\Bssco\Desktop\iLEAPP-main> python.exe .\ileappGUI.py
Traceback (most recent call last):
  File "C:\Users\Bssco\Desktop\iLEAPP-main\ileappGUI.py", line 363, in <module>
    pickModules()
  File "C:\Users\Bssco\Desktop\iLEAPP-main\ileappGUI.py", line 22, in pickModules
    loader = plugin_loader.PluginLoader()
  File "C:\Users\Bssco\Desktop\iLEAPP-main\plugin_loader.py", line 24, in __init__
    self._load_plugins()
  File "C:\Users\Bssco\Desktop\iLEAPP-main\plugin_loader.py", line 38, in _load_plugins
    mod_artifacts = getattr(mod, '__artifacts_v2__', None) or getattr(mod, '__artifacts__', None)
  File "C:\Python_3.10.2\lib\importlib\util.py", line 247, in __getattribute__
    self.__spec__.loader.exec_module(self)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\Bssco\Desktop\iLEAPP-main\scripts\artifacts\booking.py", line 901
    tmp = f'Check-in: {tmp.strftime('%Y-%m-%d')}'
                                     ^
SyntaxError: f-string: unmatched '('
PS C:\Users\Bssco\Desktop\iLEAPP-main>

removing the booking.py from the artifacts folder fixes the error and allows the GIU to appear and iLEAPP to be used.

**Comment by abrignoni** [comment]
<img width="434" alt="Screenshot 2024-07-05 at 11 16 26 AM" src="https://github.com/abrignoni/iLEAPP/assets/28718987/0cd04599-478c-417e-806a-6a53e02ce177">

It seems the nested single quotations are causing problems in your setup. What Python version are you using?
As of now the GUI opens in my Windows 11 and macOS installs. I'm using Python 3.12.1

Try this change and let me know if it works for you. If it does I will merge it.
<img width="455" alt="Screenshot 2024-07-05 at 11 17 11 AM" src="https://github.com/abrignoni/iLEAPP/assets/28718987/f57d09f3-247d-4935-997c-979e84ac3fea">
