### ISSUE TITLE
Install errors

### ISSUE THREAD

**Issue by huddledfiber** [abrignoni/iLEAPP#800]
Followed all the suggestions in the PDF and in the other post in here.  Microsoft stuff installed and up to date.  Newest version of ileapp downloaded today.  Tried in both the admin and non-admin command prompts.  Get this issue every time I try to install the requirements.

C:\Standalone\iLEAPP-main>py -m pip install -r requirements.txt
Collecting astc_decomp_faster (from -r requirements.txt (line 1))
  Using cached astc_decomp_faster-1.1.2-cp312-cp312-win_amd64.whl.metadata (3.1 kB)
Requirement already satisfied: bencoding in c:\users\tom\appdata\local\programs\python\python312\lib\site-packages (from -r requirements.txt (line 2)) (0.2.6)
Collecting biplist (from -r requirements.txt (line 3))
  Using cached biplist-1.0.3.tar.gz (21 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [49 lines of output]
      C:\Users\tom\AppData\Local\Programs\Python\Python312\Lib\site-packages\setuptools\_distutils\dist.py:268: UserWarning: Unknown distribution option: 'test_suite'
        warnings.warn(msg)
      C:\Users\tom\AppData\Local\Programs\Python\Python312\Lib\site-packages\setuptools\_distutils\dist.py:268: UserWarning: Unknown distribution option: 'tests_require'
        warnings.warn(msg)
      running egg_info
      creating C:\Users\tom\AppData\Local\Temp\pip-pip-egg-info-tmsfnlxv\biplist.egg-info
      writing C:\Users\tom\AppData\Local\Temp\pip-pip-egg-info-tmsfnlxv\biplist.egg-info\PKG-INFO
      writing dependency_links to C:\Users\tom\AppData\Local\Temp\pip-pip-egg-info-tmsfnlxv\biplist.egg-info\dependency_links.txt
      writing top-level names to C:\Users\tom\AppData\Local\Temp\pip-pip-egg-info-tmsfnlxv\biplist.egg-info\top_level.txt
      writing manifest file 'C:\Users\tom\AppData\Local\Temp\pip-pip-egg-info-tmsfnlxv\biplist.egg-info\SOURCES.txt'
      reading manifest file 'C:\Users\tom\AppData\Local\Temp\pip-pip-egg-info-tmsfnlxv\biplist.egg-info\SOURCES.txt'
      reading manifest template 'MANIFEST.in'
      adding license file 'LICENSE'
      adding license file 'AUTHORS'
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\tom\AppData\Local\Temp\pip-install-ckxtu19m\biplist_906c9fbe39264470b71fb967723385e7\setup.py", line 25, in <module>
          setup(
        File "C:\Users\tom\AppData\Local\Programs\Python\Python312\Lib\site-packages\setuptools\__init__.py", line 108, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\tom\AppData\Local\Programs\Python\Python312\Lib\site-packages\setuptools\_distutils\core.py", line 184, in setup
          return run_commands(dist)
                 ^^^^^^^^^^^^^^^^^^
        File "C:\Users\tom\AppData\Local\Programs\Python\Python312\Lib\site-packages\setuptools\_distutils\core.py", line 200, in run_commands
          dist.run_commands()
        File "C:\Users\tom\AppData\Local\Programs\Python\Python312\Lib\site-packages\setuptools\_distutils\dist.py", line 970, in run_commands
          self.run_command(cmd)
        File "C:\Users\tom\AppData\Local\Programs\Python\Python312\Lib\site-packages\setuptools\dist.py", line 945, in run_command
          super().run_command(command)
        File "C:\Users\tom\AppData\Local\Programs\Python\Python312\Lib\site-packages\setuptools\_distutils\dist.py", line 989, in run_command
          cmd_obj.run()
        File "C:\Users\tom\AppData\Local\Programs\Python\Python312\Lib\site-packages\setuptools\command\egg_info.py", line 310, in run
          self.find_sources()
        File "C:\Users\tom\AppData\Local\Programs\Python\Python312\Lib\site-packages\setuptools\command\egg_info.py", line 318, in find_sources
          mm.run()
        File "C:\Users\tom\AppData\Local\Programs\Python\Python312\Lib\site-packages\setuptools\command\egg_info.py", line 544, in run
          self.prune_file_list()
        File "C:\Users\tom\AppData\Local\Programs\Python\Python312\Lib\site-packages\setuptools\command\egg_info.py", line 610, in prune_file_list
          base_dir = self.distribution.get_fullname()
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\tom\AppData\Local\Programs\Python\Python312\Lib\site-packages\setuptools\_core_metadata.py", line 266, in get_fullname
          return _distribution_fullname(self.get_name(), self.get_version())
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\tom\AppData\Local\Programs\Python\Python312\Lib\site-packages\setuptools\_core_metadata.py", line 284, in _distribution_fullname
          canonicalize_version(version, strip_trailing_zero=False),
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      TypeError: canonicalize_version() got an unexpected keyword argument 'strip_trailing_zero'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the

**Comment by JamesHabben** [comment]
can you share your `pip list` output?

**Comment by huddledfiber** [comment]
I finally got it installed with some guidance from Heather Charpentier.

**Comment by JamesHabben** [comment]
Can you share any info about how you solved it? That can help others in the future who may search and find they are having the same issue.

**Comment by abrignoni** [comment]
Apparently the answer was uninstall all and reinstall from scratch

**Comment by huddledfiber** [comment]
Sorry, didn't see this. He is correct. I went back and forth with Heather
Charpentier trying to figure out some issues. I had to uninstall all my
Python versions and the Microsoft software. The only thing varied from
Heather was I had to run admin version of terminal to install the
requirements. Thanks for the software. I love it.

Tom

**Comment by JamesHabben** [comment]
Glad you got it worked out and thanks for sharing back. I was asking for the `pip list` because it was looking like you may have had some out of date dependencies. uninstalling it all and reinstalling would have likely updated those, but we can't know for sure. Closing this issue since its resolved.
